PresentationLayer/Models/LevelViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace PresentationLayer.Models
{
    public class LevelViewModel
    {
        public int LevelId { get; set; }
        public DateTime Year { get; set; }
        public string Semester { get; set; }
        public string Description { get; set; }
    }
}

PresentationLayer/Controllers/LevelController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using PagedList;
using System.Web.Mvc;
using BusinessLayer;
using CoreLayer;
using PresentationLayer.Models;

namespace PresentationLayer.Controllers
{
    public class LevelController : Controller
    {
        //
        // GET: /Level/

        LevelService levelService = new LevelService();

        public ActionResult Index(string sortOrder, string currentFilter, string searchString, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.YearSortParm = sortOrder == "year_asc" ? "year_dsc" : "year_asc";
            ViewBag.SemesterSortParm = sortOrder == "semester_asc" ? "semester_dsc" : "semester_asc";
            ViewBag.DescriptionSortParm = sortOrder == "desc_asc" ? "desc_dsc" : "desc_asc";
            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }
            ViewBag.currentFilter = searchString;
            int pageSize = 3;
            int pageNumber = (page ?? 1);

            var Levels = levelService.GetAllLevels(sortOrder, searchString);
            return View(Levels.ToPagedList(pageNumber, pageSize));
        }

        public ActionResult CreateNewLevel()
        {
            return View();
        }

        [HttpPost]
        public ActionResult SaveLevel(LevelViewModel LevelData)
        {

            levelService = new LevelService();
            Level Level = new Level()
            {
                Year = LevelData.Year,
                Semester=LevelData.Semester,
                Description=LevelData.Description,                 
                InsertedDate = DateTime.Now,
            };
            levelService.SaveLevel(Level);
            return View(LevelData);
        }


        public ActionResult UpdateLevel(LevelViewModel newLevelData)
        {
            Level level = new Level()
            {
                LevelId = newLevelData.LevelId,
                Year = newLevelData.Year,
                Semester = newLevelData.Semester,
                Description = newLevelData.Description,
                InsertedDate = DateTime.Now
            };
            levelService.UpdateLevel(level);
            return RedirectToAction("Index");
        }
        public ActionResult DeleteLevel(int LevelId)
        {
            try
            {
                levelService.DeleteLevel(LevelId);
            }
            catch
            {
                return View();
            }

            return RedirectToAction("Index");
        }

        public ActionResult Edit(int LevelId)
        {
            Level level = levelService.GetLevelById(LevelId);
            LevelViewModel levelViewModel = new LevelViewModel()
            {
                LevelId = level.LevelId,
                Year = level.Year,
                Semester = level.Semester,
                Description = level.Description,
            };
            return View(levelViewModel);
        }
    }
}

PresentationLayer/Views/Level/CreateNewLevel.cshtml
@model PresentationLayer.Models.LevelViewModel
@{
    ViewBag.Title = "CreateNewLevel";
    }

    <!-- BOOTSTRAP STYLES-->
    <link href="~/assets/css/bootstrap.css" rel="stylesheet" />
    <!-- FONTAWESOME STYLES-->
    <link href="~/assets/css/font-awesome.css" rel="stylesheet" />
    <!-- CUSTOM STYLES-->
    <link href="~/assets/css/custom.css" rel="stylesheet" />
    <!-- GOOGLE FONTS-->
    <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css' />
<link href="~/assets/css/registration.css" rel="stylesheet" />
    <div id="wrapper">
     <div>
       @Html.Partial("~/Views/Shared/navigator.cshtml")                
     </div>
     <div id="page-wrapper">
            <div id="page-inner">

@using (Html.BeginForm("SaveLevel", "Level", FormMethod.Post))
{ 
        <h2>Form To Create New Level</h2>
             <div class="form-group">
                @Html.LabelFor(x=> x.Year)
                @Html.EditorFor(x=> x.Year)
            </div>
            <div class="form-group">
                @Html.LabelFor(x=> x.Semester)
                @Html.EditorFor(x=> x.Semester)
            </div>
            <div class="form-group">
                @Html.LabelFor(x=> x.Description)
                @Html.EditorFor(x=> x.Description)
            </div>
                    <button type="submit">Create New Level</button>
                      
}
                </div>
         </div>
        </div>
   
<!-- JQUERY SCRIPTS -->
    <script src="~/assets/js/jquery-1.10.2.js"></script>
    <!-- BOOTSTRAP SCRIPTS -->
    <script src="~/assets/js/bootstrap.min.js"></script>
    <!-- METISMENU SCRIPTS -->
    <script src="~/assets/js/jquery.metisMenu.js"></script>
    <!-- CUSTOM SCRIPTS -->
    <script src="~/assets/js/custom.js"></script>

PresentationLayer/Views/Level/DeleteLevel.cshtml
@{
    ViewBag.Title = "DeleteLevel";
}

<h2>DeleteLevel</h2>

PresentationLayer/Views/Level/Edit.cshtml
@model PresentationLayer.Models.LevelViewModel
@{
    ViewBag.Title = "Edit";
}
    <!-- BOOTSTRAP STYLES-->
    <link href="~/assets/css/bootstrap.css" rel="stylesheet" />
    <!-- FONTAWESOME STYLES-->
    <link href="~/assets/css/font-awesome.css" rel="stylesheet" />
    <!-- CUSTOM STYLES-->
    <link href="~/assets/css/custom.css" rel="stylesheet" />
    <!-- GOOGLE FONTS-->
    <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css' />
<link href="~/assets/css/registration.css" rel="stylesheet" />
    <div id="wrapper">
     <div>
       @Html.Partial("~/Views/Shared/navigator.cshtml")                
     </div>
     <div id="page-wrapper">
            <div id="page-inner">
<h2>Edit</h2>
@using (Html.BeginForm("UpdateLevel", "Level", FormMethod.Post))
{ 
    
            @Html.HiddenFor(x=>x.LevelId)
             <div class="form-group">
               @Html.LabelFor(x=> x.Year)
               @Html.EditorFor(x=> x.Year)
            </div>
            <div class="form-group">
               @Html.LabelFor(x=> x.Semester)
               @Html.EditorFor(x=> x.Semester)
            </div>
            <div class="form-group">
               @Html.LabelFor(x=> x.Description)
               @Html.EditorFor(x=> x.Description)
           </div>
                    <button type="submit">Update Level</button>
                     
}
                </div>
         </div>
        </div>
<!-- JQUERY SCRIPTS -->
    <script src="~/assets/js/jquery-1.10.2.js"></script>
    <!-- BOOTSTRAP SCRIPTS -->
    <script src="~/assets/js/bootstrap.min.js"></script>
    <!-- METISMENU SCRIPTS -->
    <script src="~/assets/js/jquery.metisMenu.js"></script>
    <!-- CUSTOM SCRIPTS -->
    <script src="~/assets/js/custom.js"></script>   

PresentationLayer/Views/Level/Index.cshtml
<!DOCTYPE html>
@model PagedList.IPagedList<CoreLayer.Level>
@using PagedList.Mvc;
@{
    ViewBag.Title = "Levels";
}
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />
        <!-- BOOTSTRAP STYLES-->
    <link href="~/assets/css/bootstrap.css" rel="stylesheet" />
    <!-- FONTAWESOME STYLES-->
    <link href="~/assets/css/font-awesome.css" rel="stylesheet" />
    <!-- CUSTOM STYLES-->
    <link href="~/assets/css/custom.css" rel="stylesheet" />
    <!-- GOOGLE FONTS-->
    <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css' />
    <link href="~/assets/css/registration.css" rel="stylesheet" />

</head>
<body>
    <div id="wrapper">
     <div>
       @Html.Partial("~/Views/Shared/navigator.cshtml")                
     </div>
     <div id="page-wrapper">
            <div id="page-inner">
             @using (Html.BeginForm("Index","Level",FormMethod.Get)){    
                     <p> 
                       Find By Name:  @Html.TextBox("SearchString",ViewBag.currentFilter as string)  
                     <input type="submit" value="Search" /></p> 
             }
                <div>
                    <table>
                        <thead>
                
                                <th>@Html.ActionLink("Year", "Index", "Level", new { sortOrder=ViewBag.NameSortParm ,currenFilter=ViewBag.currentFilter },"")</th>
                                <th>@Html.ActionLink("Semester", "Index", "Level", new { sortOrder=ViewBag.descSortParm ,currenFilter=ViewBag.currentFilter },"")</th>
                                <th>@Html.ActionLink("Description", "Index", "Level", new { sortOrder=ViewBag.deptheadSortParm ,currenFilter=ViewBag.currentFilter },"")</th>
                   
                
                            @foreach (var item in Model)
                            { 
                            <tr>
                                <td>@item.Year</td>
                                <td>@item.Semester</td>
                                <td>@item.Description</td>
                                <td>@Html.ActionLink("Edit","Edit","Level", new{LevelId = item.LevelId},"")</td>
                                <td>@Html.ActionLink("Delete","DeleteLevel","Level", new{LevelId = item.LevelId},"")</td>
                
                            </tr>
                            }        
                        </thead>
                    </table>
            
                    page @(Model.PageCount<Model.PageNumber?0:
                        Model.PageNumber) of @Model.PageCount
                    @Html.PagedListPager(Model,page=>Url.Action
                   ("Index","Level",new {page,sortOrder=ViewBag.currentSort,currentFilter=ViewBag.currentFilter}))
                </div>
             <div class="col-md-4">
                        <div class="btn btn-danger btn-lg btn-block">@Html.ActionLink("Create New Level","CreateNewLevel","Level")</div>
                    </div>
        </div>
    </div>
    </div>
    <!-- JQUERY SCRIPTS -->
    <script src="~/assets/js/jquery-1.10.2.js"></script>
    <!-- BOOTSTRAP SCRIPTS -->
    <script src="~/assets/js/bootstrap.min.js"></script>
    <!-- METISMENU SCRIPTS -->
    <script src="~/assets/js/jquery.metisMenu.js"></script>
    <!-- CUSTOM SCRIPTS -->
    <script src="~/assets/js/custom.js"></script>
</body>

</html>

PresentationLayer/Views/Level/SaveLevel.cshtml
@model PresentationLayer.Models.LevelViewModel
@{
    ViewBag.Title = "SaveLevel";
    }

    <!-- BOOTSTRAP STYLES-->
    <link href="~/assets/css/bootstrap.css" rel="stylesheet" />
    <!-- FONTAWESOME STYLES-->
    <link href="~/assets/css/font-awesome.css" rel="stylesheet" />
    <!-- CUSTOM STYLES-->
    <link href="~/assets/css/custom.css" rel="stylesheet" />
    <!-- GOOGLE FONTS-->
    <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css' />
<link href="~/assets/css/registration.css" rel="stylesheet" />
    <div id="wrapper">
     <div>
       @Html.Partial("~/Views/Shared/navigator.cshtml")                
     </div>
     <div id="page-wrapper">
            <div id="page-inner">
<table>
    <tbody>
        <th><h2>Following Level Information Has Been Saved</h2></th>
        <tr>
            <td>@Html.LabelFor(x => x.Year) :</td>
            <td>@Model.Year</td>
        </tr>
        <tr>
            <td>@Html.LabelFor(x => x.Semester) :</td>
            <td>@Model.Semester</td>
        </tr>
        <tr>
            <td>@Html.LabelFor(x => x.Description) :</td>
            <td>@Model.Description</td>
        </tr>
    </tbody>
</table>
                </div>
         </div>
        </div>
<!-- JQUERY SCRIPTS -->
    <script src="~/assets/js/jquery-1.10.2.js"></script>
    <!-- BOOTSTRAP SCRIPTS -->
    <script src="~/assets/js/bootstrap.min.js"></script>
    <!-- METISMENU SCRIPTS -->
    <script src="~/assets/js/jquery.metisMenu.js"></script>
    <!-- CUSTOM SCRIPTS -->
    <script src="~/assets/js/custom.js"></script>